#include <iostream>

class Empty{};
/*
 * C++ 03(might be generated by compiler)
 * 1. default constructor (generated only if no constructor is declared by user)
 * 2. copy constructor (generated only if no 3,4,5,6 declared by user)
 * 3. copy assigment operator (generated only if 3,4,5, 6 not declared by user)
 * 4. destructor
 *
 * C++ 11
 * 5. move constructor  (generated only if 2,3,4,6 not declared by user)
 * 6. move assigment operator (generated only if 2,3,4,5 not declared by user)
 */

class EmptyByCompiler
{
    //C++ 03
    EmptyByCompiler();                                      //  default constructor
    EmptyByCompiler(const EmptyByCompiler&);                //  copy constructor
    EmptyByCompiler& operator=(const EmptyByCompiler&);     //  copy assigment operator
    ~EmptyByCompiler();                                     //  destructor

    // C++ 11
    EmptyByCompiler(EmptyByCompiler&&);                     //  move constructor
    EmptyByCompiler& operator=(EmptyByCompiler&&);          //  move assigment operator
};

int main()
{
    std::cout << "Hello, World!" << std::endl;
    return 0;
}